basePath: /api/v1
definitions:
  errcode.Error:
    type: object
host: localhost:8089
info:
  contact:
    email: 2391815999@qq.com
    name: API Support
    url: http://www.github.com
  description: jackson366 使用chatglm4的能力所开发的AI项目
  license:
    name: The MIT License (MIT)
    url: http://www.github.com
  termsOfService: http://www.github.com
  title: AI_Project_DEMO
  version: "1.0"
paths:
  /login:
    post:
      parameters:
      - description: 用户账号
        in: body
        name: UserAccount
        required: true
        schema:
          type: string
      - description: 用户密码
        in: body
        name: UserPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 用户登录
swagger: "2.0"
